# This follows the order from the [Prettier Options
# Documentation](https://prettier.io/docs/en/options.html)
printWidth: 80
tabWidth: 2
useTabs: true
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingCommas: es5
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
# rangeStart: 0
# rangeEnd: Infinity # Infinity is not integer
# parser: # Infer pls
# filepath:
requirePragma: false
insertPragma: false
proseWrap: always
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf
